laravel/dusk

src/Console/DuskCommand.php
My dev path has spaces in, so wouldn't work without the quotes
=> Wrap path in quotes

src/Concerns/InteractsWithCookies.php
More details: https://github.com/laravel/dusk/issues/8
=> Fixed unused and incorrect cookie expiry variable

src/Concerns/WaitsForElements.php
=> Fix code style

src/Concerns/MakesAssertions.php
This class isn't being used within the trait
=> Remove unused WebDriverBy class

src/Concerns/InteractsWithElements.php, src/Concerns/MakesAssertions.php
I've replaced jQuery or $ with jQuery.find.
See https://jsperf.com/jquery-vs-sizzle-benchmark for performance comparison.
=> use jQuery.find (sizzle)

src/Concerns/InteractsWithElements.php
=> Silly typo or was it on purpose?

src/Console/DuskCommand.php
set process timeout to 0 to disable it - see #63
=> disabled process timeout

src/Console/DuskCommand.php
See https://github.com/laravel/dusk/issues/85
I just returned the callback return from the ProcessBuilder.
=> Exit code on test failure

src/Concerns/InteractsWithElements.php
if no value is passed, a random option will be picked.
=> allow user to select a random option from dropdown field

src/Concerns/MakesAssertions.php
Added assertHasQueryStringParam, assertMissingQueryStringParam and assertQueryStringValue.
=> Added query string assertions

src/Console/InstallCommand.php
Please see the discussion in #139
=> allow to run dusk:install as upgrade

src/Concerns/InteractsWithElements.php
I found a need for some offset base dragging functionality and added the following few methods to allow me to do that. I thought they may be a useful addition to the core so just submitting here in case you are interested. 
No stress if you aren't keen.
=> Added drag by offset functionality

src/Console/stubs/test.stub
help with autocomplete and such
=> typehint `Browser` in stub

src/Concerns/MakesAssertions.php
Add an assertPathIsNot function, which does the opposite of assertPathIs.
=> Add assertPathIsNot function

src/Browser.php
This seems to be missing from Dusk, and is useful for testing browser state.
=> Support back button

src/Console/DuskCommand.php
=> Revert "Attempt to solve TTY issue" / [WIP] Supress Symphony exception

composer.json
I was thinking about this yesterday and then #230 showed up to confirm my thoughts.
=> [1.0.13] Add Illuminate/Console as dependency

src/SupportsChrome.php, tests/ChromeDriverTest.php
Some developers might want to use a older or more recent Chrome driver.
=> Add the ability to use a custom Chrome driver file

src/Concerns/WaitsForElements.php
The current implementation is broken. This PR fixes it.
(I am to git-blame for the error - I take full responsibility)
=> Fix waitForReload() method

src/Browser.php
Add `$browser`, `$driver`, `$resolver` and `$page` to tinker context.
=> Add tinker context variables

src/Concerns/InteractsWithElements.php
fixes #180 
Codeception had the same issue, i've used the same solution here:
https://github.com/Codeception/Codeception/issues/1823
=> fix phantomjs attach issue

src/Console/InstallCommand.php
Since the constructor do not does nothing on that command would be better remove him in order to keep the code clean. 😊
=> Removes unused constructor

composer.json
=> [1.0] Some composer adjustments.

src/ElementResolver.php
It did not find the buttons with HTML like.
<input type="button" value="Some text"/>
=> Add type="button" to find

src/Concerns/MakesAssertions.php
Original methods could assert if a button is visible or not.
=> Added assertSeeButton() and assertDontSeeButton()

src/Chrome/ChromeProcess.php, src/Chrome/SupportsChrome.php, src/TestCase.php, tests/ChromeProcessTest.php
- Move the logic of building the Chrome process to it's own class;
- Add unit tests for building Chrome Process;
- Implement @glatzor solution for #341 only for Linux and Mac;
=> Chrome Process refactored

tests/BrowserTest.php
Currently, the test suite doesn't pass - this PR fixes that.
=> Fix broken console log tests

src/Console/DuskCommand.php
=> Revert "extend base .env values instead of redefining in .env.dusk.local"

src/Concerns/MakesAssertions.php
=> Add asserts to validate URL fragments

src/Chrome/ChromeProcess.php
=> Replace ProcessBuilder with Process and remove redundant method.

src/Concerns/MakesAssertions.php
Add assertion for check is a possible hidden element present in DOM
=> Update MakesAssertions add present assert

src/Concerns/ProvidesBrowser.php
Missing class import from #442 (didn't expect it wasn't covered by the tests).
With this changes, TestCase using the traits now works fine.
=> [2.0] Add missing import.

src/Concerns/MakesAssertions.php
Fixes https://github.com/laravel/dusk/issues/447
=> Fix bug with assertSelectHasOptions() and duplicate values

tests/MakesAssertionsTest.php
To end the madness (https://github.com/laravel/dusk/pull/461).
=> Add assertQueryStringHas() tests

src/Concerns/ProvidesBrowser.php
=> Revert "Prevent screenshot and console filename collisions"

src/Concerns/MakesAssertions.php, tests/MakesAssertionsTest.php, tests/stubs/route.php
Adds tests for:
- assertTitle()
- assertTitleContains()
- assertPathBeginsWith()
- assertPathIsNot()
- assertFragmentIs()
- assertFragmentBeginsWith()
- assertFragmentIsNot()
- assertRouteIs()
- assertQueryStringMissing()
=> Add assertion tests

src/Concerns/MakesAssertions.php
Provides clearer error messages for failed assertions.
=> Customize input value assertion error messages

src/Concerns/MakesAssertions.php, tests/MakesAssertionsTest.php
Provides clearer error messages for failed assertions.
=> Customize URL assertion error messages

src/Concerns/WaitsForElements.php
- add custom error message for `waitForLink()`
- add custom error message for `waitForLocation()`
- pass a custom error message to `waitUntil()`
=> add better error messages

src/Concerns/ProvidesBrowser.php, src/Concerns/WaitsForElements.php, src/ElementResolver.php
additionally update to a FQN for an existing `@throws` line.
=> add missing `@throws` to docblocks

.travis.yml
Chromedriver was out of date which was causing some issues.
Fixes https://github.com/laravel/dusk/issues/570
=> [4.0] Update Chromedriver

src/Console/DuskCommand.php
Fix #609: added support for 'phpunit.dusk.xml.dist'
=> [5.0] added support for 'phpunit.dusk.xml.dist'

composer.json
=> [5.x] Allow Symfony 5.x

src/Concerns/WaitsForElements.php
=> [5.0] use FQN

src/Concerns/InteractsWithElements.php, tests/Concerns/InteractsWithElementsTest.php
This handles JS quoting a little bit better.
=> [6.x] Bugfix quoting for InteractsWithElements::value

src/DuskServiceProvider.php
The risk of running Dusk in production revolve assigning unsecure
routing to assist testing with Dusk.
=> [5.x] Avoid throwing exception on production.

src/Browser.php
Support navigating forward in the browser
Closes #623
=> Support navigating forward in the browser

src/Concerns/InteractsWithAuthentication.php, src/DuskServiceProvider.php
This fix failing test when running Dusk within Package Development environment.
e.g: https://travis-ci.org/github/orchestral/testbench-dusk/builds/686544633
=> [6.x] Domain routing should only be optional.

src/Console/ChromeDriverCommand.php
=> [6.x] Fixed proxy for getting latest version

CHANGELOG.md
=> [6.x] add missing change for v6.8.0

.github/workflows/tests.yml, composer.json
=> [6.x] PHP 8 Support

src/Concerns/MakesAssertions.php, src/Concerns/MakesUrlAssertions.php, tests/MakesAssertionsTest.php, tests/MakesUrlAssertionsTest.php
- Align docblocks with recent update to docs
- Correctly order assertions and accompanying tests
- Correctly order URL assertions and accompanying tests
=> Align docblocks with recent update to docs

src/Concerns/MakesAssertions.php
RE: https://github.com/laravel/docs/commit/d96e6f9
=> [6.x] Update docblocks

src/Browser.php
=> Use $browser given from closure to received scoped selector.

.github/workflows/tests.yml, composer.json, tests/Concerns/InteractsWithElementsTest.php
=> [7.x] PHPUnit v10

src/Concerns/WaitsForElements.php
=> [6.x] Improves docblock

src/Browser.php
I probably missed this out when creating the original PR #846
=> [6.x] Add $seconds options to Browser::elseWhenAvailable()

composer.json, src/Chrome/ChromeProcess.php, src/Console/ChromeDriverCommand.php, src/OperatingSystem.php, tests/ChromeProcessTest.php
=> [7.x] Refactor PR to match changes to PR #876

src/Console/DuskCommand.php
=> [6.x] Refactor redundant purging methods.

src/Browser.php, src/Chrome/ChromeProcess.php, src/Concerns/InteractsWithAuthentication.php, src/Concerns/InteractsWithElements.php, src/Concerns/InteractsWithMouse.php, src/Concerns/MakesAssertions.php, src/Concerns/MakesUrlAssertions.php, src/ElementResolver.php, src/Http/Controllers/UserController.php, src/Page.php
Found this type hints missing, one miss import and a var name changed.
Hope that helps.
=> Add Missing Type Hints and Fix Some Typos

.github/workflows/tests.yml, CHANGELOG.md, composer.json, src/Concerns/WaitsForElements.php
=> Merge into master

.github/workflows/tests.yml, composer.json
=> [7.x] Drop old PHP and Laravel versions

UPGRADE.md
Ignore failing tests here. Will be resolved when https://github.com/laravel/dusk/pull/993 is merged.
=> Upgrade guide for 7.x

src/Chrome/ChromeProcess.php
=> Remove extra Directory Separator from ChromeProcess

src/Console/ChromeDriverCommand.php
Fixes https://github.com/laravel/dusk/issues/1000
=> [6.x] Fix updated Mac image name

composer.json, src/Chrome/ChromeProcess.php, src/Console/ChromeDriverCommand.php, tests/ChromeProcessTest.php
=> Revert "Allow custom chromedriver install path"

src/Console/stubs/component.stub, src/Console/stubs/page.stub, src/Console/stubs/test.stub, stubs/DuskTestCase.stub, stubs/ExampleTest.stub, stubs/HomePage.stub, stubs/Page.stub
Please check https://github.com/laravel/laravel/pull/6010 for details about this pull request.
=> [7.x] Uses PHP Native Type Declarations 🐘 

.github/workflows/tests.yml
=> Test PHPUnit 10

.gitattributes, .github/workflows/static-analysis.yml, composer.json, phpstan.neon.dist, src/Concerns/InteractsWithCookies.php, src/Concerns/ProvidesBrowser.php, src/Concerns/WaitsForElements.php, src/Console/ChromeDriverCommand.php, src/Console/DuskCommand.php
This pull request adds type checking to this repository.
=> [7.x] Adds type checking

.gitattributes
=> [7.x] Export ignore `testbench.yaml` file

.github/workflows/tests.yml
=> PHP 8.3 build

.github/workflows/browser-tests.yml, composer.json, phpunit.dusk.xml.dist, phpunit.xml.dist, phpunit9.xml.dist, testbench.yaml, tests/Browser/BrowserTest.php, tests/Browser/DuskTestCase.php, tests/Browser/console/.gitignore, tests/Browser/screenshots/.gitignore, tests/Browser/source/.gitignore, tests/Feature/SupportsChromeTest.php, tests/Unit/BrowserTest.php, tests/Unit/ChromeProcessTest.php, tests/Unit/ComponentTest.php, tests/Unit/ElementResolverTest.php, tests/Unit/MakesAssertionsTest.php, tests/Unit/MakesUrlAssertionsTest.php, tests/Unit/OperatingSystemTest.php, tests/Unit/ProvidesBrowserTest.php, tests/Unit/WaitsForElementsTest.php
Run browser tests directly within Laravel Dusk using Testbench CLI
=> Tests improvements

.github/workflows/tests.yml, src/Console/DuskCommand.php
=> Fixes unknown option "--ansi" and "--no-ansi"
